// background.js

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'syncCookies') {
    handleSync(request.serverUrl, request.adminPassword)
      .then(result => sendResponse(result))
      .catch(error => {
        console.error("Errore sync:", error);
        sendResponse({ success: false, message: error.message || String(error) });
      });
    return true; // Indica che invieremo la risposta in modo asincrono
  }
});

async function handleSync(serverUrl, adminPassword) {
  // 1. Leggiamo i cookie di YouTube
  const cookies = await new Promise((resolve) => {
    chrome.cookies.getAll({ domain: "youtube.com" }, resolve);
  });

  if (!cookies || cookies.length === 0) {
    throw new Error("Nessun cookie trovato per YouTube. Assicurati di fare il login su youtube.com nel tuo browser.");
  }

  // 2. Li formattiamo nel formato Netscape
  const netscapeText = formatToNetscape(cookies);

  // 3. Facciamo il login al Raspberry per ottenere il Token
  const loginRes = await fetch(`${serverUrl}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ username: "admin", password: adminPassword })
  });

  if (!loginRes.ok) {
    throw new Error("Login al Raspberry fallito. Verifica indirizzo o password.");
  }

  const loginData = await loginRes.json();
  const token = loginData.token;

  if (!token) {
    throw new Error("Il server non ha restituito un token valido.");
  }

  // 4. Inviamo i cookie al server
  const uploadRes = await fetch(`${serverUrl}/api/admin/youtube-cookies`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`
    },
    body: JSON.stringify({ cookiesText: netscapeText })
  });

  if (!uploadRes.ok) {
    const errData = await uploadRes.json().catch(() => ({}));
    throw new Error(errData.message || "Errore durante l'invio dei cookie al server.");
  }

  const uploadData = await uploadRes.json();
  return { success: true, message: `Caricati ${cookies.length} cookie di cui ${uploadData.cookies?.analysis?.sessionCookieCount || '?'} di sessione!` };
}

function formatToNetscape(cookies) {
  let output = "# Netscape HTTP Cookie File\n# Generated by ClearWave Sync\n\n";
  for (const cookie of cookies) {
    const domain = cookie.domain;
    const includeSubdomains = domain.startsWith('.') ? "TRUE" : "FALSE";
    const path = cookie.path;
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expiration = cookie.session ? "0" : Math.floor(cookie.expirationDate || 0);
    const name = cookie.name;
    const value = cookie.value;

    output += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
  }
  return output;
}
