const storageKey = "clearwave-state";
const safeLinkImportMaxTracks = 5000;
const sessionLinkImportMaxTracks = 5000;
const authTokenStorageKey = "clearwave-auth-token";
const catalogPageSize = 20;
const defaultState = {
  search: "",
  genre: "all",
  source: "all",
  catalogPage: 1,
  mood: "all",
  license: "all",
  useCase: "all",
  attributionOnly: false,
  uiTheme: "dark",
  adminAccessCode: "clearwave-admin",
  currentAccountId: "admin",
  accounts: [
    { id: "admin", name: "Amministratore", role: "admin" },
    { id: "user", name: "Utente", role: "user" },
  ],
  projectName: "",
  projectUsage: "ADV digital",
  selectedIds: [],
  favoriteIds: [],
  queueIds: [],
  activePlaylistId: "real-songs",
  playerVolume: 0.8,
  shuffleEnabled: false,
  repeatMode: "off",
};

const playerIcons = {
  shuffle: "⤨",
  previous: "‹‹",
  play: "▶",
  pause: "Ⅱ",
  next: "››",
  repeat: "↻",
  repeatOne: "↻1",
};

const dom = {
  searchInput: document.querySelector("#searchInput"),
  accountSelect: document.querySelector("#accountSelect"),
  accountNameInput: document.querySelector("#accountNameInput"),
  accountRoleSelect: document.querySelector("#accountRoleSelect"),
  createAccountButton: document.querySelector("#createAccountButton"),
  removeAccountButton: document.querySelector("#removeAccountButton"),
  openAuthButton: document.querySelector("#openAuthButton"),
  sidebarLogoutButton: document.querySelector("#sidebarLogoutButton"),
  topbarLogoutButton: document.querySelector("#topbarLogoutButton"),
  accountStatus: document.querySelector("#accountStatus"),
  authGate: document.querySelector("#authGate"),
  loginUsername: document.querySelector("#loginUsername"),
  loginPassword: document.querySelector("#loginPassword"),
  loginButton: document.querySelector("#loginButton"),
  logoutButton: document.querySelector("#logoutButton"),
  authStatus: document.querySelector("#authStatus"),
  trackContextMenu: document.querySelector("#trackContextMenu"),
  contextQueueButton: document.querySelector("#contextQueueButton"),
  settingsPanel: document.querySelector("#impostazioni"),
  settingsStatus: document.querySelector("#settingsStatus"),
  accountsList: document.querySelector("#accountsList"),
  currentPasswordInput: document.querySelector("#currentPasswordInput"),
  newPasswordInput: document.querySelector("#newPasswordInput"),
  changePasswordButton: document.querySelector("#changePasswordButton"),
  passwordStatus: document.querySelector("#passwordStatus"),
  currentRoleBadge: document.querySelector("#currentRoleBadge"),
  themeToggleButton: document.querySelector("#themeToggleButton"),
  genreSelect: document.querySelector("#genreSelect"),
  sourceSelect: document.querySelector("#sourceSelect"),
  moodSelect: document.querySelector("#moodSelect"),
  licenseSelect: document.querySelector("#licenseSelect"),
  useCaseSelect: document.querySelector("#useCaseSelect"),
  attributionToggle: document.querySelector("#attributionToggle"),
  trackGrid: document.querySelector("#trackGrid"),
  catalogPagination: document.querySelector("#catalogPagination"),
  resultsSummary: document.querySelector("#resultsSummary"),
  libraryStatus: document.querySelector("#libraryStatus"),
  discoverySearchInput: document.querySelector("#discoverySearchInput"),
  discoveryRightsMode: document.querySelector("#discoveryRightsMode"),
  discoveryProviderSelect: document.querySelector("#discoveryProviderSelect"),
  discoverySearchButton: document.querySelector("#discoverySearchButton"),
  bulkImportButton: document.querySelector("#bulkImportButton"),
  importLinkInput: document.querySelector("#importLinkInput"),
  importLinkButton: document.querySelector("#importLinkButton"),
  sessionImportButton: document.querySelector("#sessionImportButton"),
  sessionUserInput: document.querySelector("#sessionUserInput"),
  sessionLoginButton: document.querySelector("#sessionLoginButton"),
  sessionLogoutButton: document.querySelector("#sessionLogoutButton"),
  sessionStatus: document.querySelector("#sessionStatus"),
  externalRiskModal: document.querySelector("#externalRiskModal"),
  externalRiskMessage: document.querySelector("#externalRiskMessage"),
  externalRiskConfirmButton: document.querySelector("#externalRiskConfirmButton"),
  externalRiskCancelButton: document.querySelector("#externalRiskCancelButton"),
  discoveryStatus: document.querySelector("#discoveryStatus"),
  bulkImportStatus: document.querySelector("#bulkImportStatus"),
  discoveryResults: document.querySelector("#discoveryResults"),
  providerPills: document.querySelector("#providerPills"),
  playlistGrid: document.querySelector("#playlistGrid"),
  playlistStatus: document.querySelector("#playlistStatus"),
  playlistFocusTitle: document.querySelector("#playlistFocusTitle"),
  playlistFocusMeta: document.querySelector("#playlistFocusMeta"),
  playlistTrackRow: document.querySelector("#playlistTrackRow"),
  queueList: document.querySelector("#queueList"),
  queueStatus: document.querySelector("#queueStatus"),
  clearQueueButton: document.querySelector("#clearQueueButton"),
  projectName: document.querySelector("#projectName"),
  projectUsage: document.querySelector("#projectUsage"),
  selectedCount: document.querySelector("#selectedCount"),
  selectedAvgBpm: document.querySelector("#selectedAvgBpm"),
  selectionList: document.querySelector("#selectionList"),
  reportOutput: document.querySelector("#reportOutput"),
  reportStatus: document.querySelector("#reportStatus"),
  copyReportButton: document.querySelector("#copyReportButton"),
  clearSelectionButton: document.querySelector("#clearSelectionButton"),
  metricTracks: document.querySelector("#metricTracks"),
  metricZero: document.querySelector("#metricZero"),
  metricUses: document.querySelector("#metricUses"),
  archiveUploadedCount: document.querySelector("#archiveUploadedCount"),
  archiveLicensedCount: document.querySelector("#archiveLicensedCount"),
  archiveMissingCount: document.querySelector("#archiveMissingCount"),
  archiveList: document.querySelector("#archiveList"),
  uploadForm: document.querySelector("#uploadForm"),
  uploadStatus: document.querySelector("#uploadStatus"),
  submitUploadButton: document.querySelector("#submitUploadButton"),
  uploadTitle: document.querySelector("#uploadTitle"),
  uploadSubtitle: document.querySelector("#uploadSubtitle"),
  uploadMood: document.querySelector("#uploadMood"),
  uploadEnergy: document.querySelector("#uploadEnergy"),
  uploadBpm: document.querySelector("#uploadBpm"),
  uploadDuration: document.querySelector("#uploadDuration"),
  uploadLicense: document.querySelector("#uploadLicense"),
  uploadLicenseDetail: document.querySelector("#uploadLicenseDetail"),
  uploadUseCases: document.querySelector("#uploadUseCases"),
  uploadFormats: document.querySelector("#uploadFormats"),
  uploadInstrument: document.querySelector("#uploadInstrument"),
  uploadStems: document.querySelector("#uploadStems"),
  uploadTags: document.querySelector("#uploadTags"),
  uploadSourceUrl: document.querySelector("#uploadSourceUrl"),
  uploadDescription: document.querySelector("#uploadDescription"),
  uploadRightsNotes: document.querySelector("#uploadRightsNotes"),
  uploadAudioFile: document.querySelector("#uploadAudioFile"),
  uploadLicenseFile: document.querySelector("#uploadLicenseFile"),
  uploadAttributionRequired: document.querySelector("#uploadAttributionRequired"),
  embeddedPlayer: document.querySelector("#embeddedPlayer"),
  embeddedPlayerTitle: document.querySelector("#embeddedPlayerTitle"),
  embeddedPlayerMeta: document.querySelector("#embeddedPlayerMeta"),
  embeddedPlayerFrame: document.querySelector("#embeddedPlayerFrame"),
  embeddedCloseButton: document.querySelector("#embeddedCloseButton"),
  playerDock: document.querySelector("#playerDock"),
  playerArt: document.querySelector("#playerArt"),
  playerTitle: document.querySelector("#playerTitle"),
  playerMeta: document.querySelector("#playerMeta"),
  playerState: document.querySelector("#playerState"),
  playerProgress: document.querySelector("#playerProgress"),
  playerSeekRange: document.querySelector("#playerSeekRange"),
  playerToggleButton: document.querySelector("#playerToggleButton"),
  playerShuffleButton: document.querySelector("#playerShuffleButton"),
  playerRepeatButton: document.querySelector("#playerRepeatButton"),
  playerPrevButton: document.querySelector("#playerPrevButton"),
  playerNextButton: document.querySelector("#playerNextButton"),
  playerVolumeRange: document.querySelector("#playerVolumeRange"),
  playerVolumeIcon: document.querySelector("#playerVolumeIcon"),
  playerVolumeValue: document.querySelector("#playerVolumeValue"),
  playerTime: document.querySelector("#playerTime"),
  playerSelectionCount: document.querySelector("#playerSelectionCount"),
  playerRailState: document.querySelector("#playerRailState"),
  playerLibraryCount: document.querySelector("#playerLibraryCount"),
  playerDiscoveryCount: document.querySelector("#playerDiscoveryCount"),
};

